### ISSUE TITLE
IANA Considerations

### ISSUE THREAD

**Issue by dthaler** [intarchboard/draft-protocol-greasing#31]
> # IANA Considerations
>
> This document has no IANA actions.

It might be helpful to provide guidance to document authors about what to put in their IANA Considerations section when asking for (say) ranges of a codepoint to be reserved for greasing.

**Comment by gorryfair** [comment]
I just saw this point, but I think the text starting: "Protocols might ask IANA..." could become a subsection and would be easier to refer people to when they propose a new registry.
